//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videoclub_project.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int idEmpleado { get; set; }
        public float salario { get; set; }
        public string cuanta_bancaria { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
