//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videoclub_project.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.productos_alquiler = new HashSet<productos_alquiler>();
            this.ventas_productos = new HashSet<ventas_productos>();
        }
    
        public int idProductos { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string portada { get; set; }
        public int nota { get; set; }
        public string edad_nota { get; set; }
        public int id_genero { get; set; }
        public int id_idioma { get; set; }
        public int id_idiomaDoblado { get; set; }
    
        public virtual generos generos { get; set; }
        public virtual idiomas idiomas { get; set; }
        public virtual idiomas idiomas1 { get; set; }
        public virtual peliculas peliculas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_alquiler> productos_alquiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas_productos> ventas_productos { get; set; }
        public virtual videojuegos videojuegos { get; set; }
    }
}
