//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videoclub_project.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public const int PELICULA = 1;
        public const int JUEGO = 2;

        public int idProductos { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string portada { get; set; }
        public int nota { get; set; }
        public string edad_nota { get; set; }
        public int id_genero { get; set; }
        public int id_idioma { get; set; }
        public int id_idiomaDoblado { get; set; }
    
        public virtual generos generos { get; set; }
        public virtual idiomas idiomas { get; set; }
        public virtual idiomas idiomas1 { get; set; }
        public virtual peliculas peliculas { get; set; }
        public virtual videojuegos videojuegos { get; set; }

        public override string ToString() {
            return titulo;
        }
    }
}
